import React, { createContext, useContext, useState, useEffect } from 'react';

export type Theme = 'light' | 'dark';
export type Language = 'vi' | 'en';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  vi: {
    // ── Navbar ──────────────────────────────────────
    home: 'Trang chủ',
    status: 'Trạng thái',
    contact: 'Liên hệ',
    login: 'Đăng nhập',
    register: 'Đăng ký ngay',
    hello: 'Xin chào,',
    profile: 'Thông tin cá nhân',
    history: 'Lịch sử gửi xe',
    reportIncident: 'Báo cáo sự cố',
    logout: 'Đăng xuất',
    // ── Settings dropdown ───────────────────────────
    settings: 'Cài đặt',
    appearance: 'Giao diện',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    language: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    // ── LandingPage ─────────────────────────────────
    heroTitle1: 'Hệ thống',
    heroTitle2: 'Quản lý Đỗ xe',
    heroTitle3: 'Thông minh',
    heroSubtitle: 'Thế hệ quản lý hạ tầng tiếp theo. Trải nghiệm sự liền mạch và tối ưu hóa không gian được dẫn dắt bởi trí tuệ nhân tạo kiến trúc.',
    bookNow: 'Đặt chỗ ngay',
    viewPricing: 'Xem Bảng giá',
    statUptime: 'Thời gian hoạt động',
    statSpots: 'Vị trí khả dụng',
    statProcessing: 'Thời gian xử lý',
    statDataPoints: 'Điểm dữ liệu',
    occupancyRate: 'Tỉ lệ lấp đầy',
    optimal: 'Tối ưu',
    coreTech: 'Công nghệ lõi',
    featuresTitle1: 'Trải nghiệm đỗ xe',
    featuresTitle2: 'không chạm',
    featuresDesc: 'Hệ thống PM System tích hợp công nghệ AI và IoT tiên tiến nhất, mang đến giải pháp quản lý bãi đỗ xe toàn diện và tự động hóa 100%.',
    feat1Title: 'Nhận diện AI tức thì',
    feat1Desc: 'Camera AI tự động đọc biển số xe trong 0.2s, mở barrier tự động không cần lấy vé giấy hay dừng chờ.',
    feat2Title: 'Bản đồ số Digital Twin',
    feat2Desc: 'Giám sát hạ tầng theo thời gian thực. Cập nhật trạng thái từng vị trí đỗ chính xác đến từng giây.',
    feat3Title: 'Thanh toán không tiền mặt',
    feat3Desc: 'Tích hợp VNPay, tự động trừ tiền qua mã QR. Khách hàng dễ dàng xuất bến mà không cần tiền mặt.',
    howItWorksTitle1: 'Quy trình',
    howItWorksTitle2: 'tối giản',
    howItWorksSubtitle: 'Chỉ với 3 bước đơn giản, mọi thủ tục gửi xe của bạn sẽ được hoàn tất hoàn toàn tự động.',
    step1Title: 'Đặt chỗ trước',
    step1Desc: 'Chọn bãi đỗ và vị trí thông qua bản đồ trực tuyến ngay trên điện thoại.',
    step2Title: 'Quét & Nhận diện',
    step2Desc: 'Hệ thống Camera AI tại cổng sẽ tự động nhận diện biển số và cấp quyền truy cập.',
    step3Title: 'Tự động thanh toán',
    step3Desc: 'Khi xe ra, hệ thống tự đối soát thời gian và trừ tiền tự động.',
    ctaTitle1: 'Sẵn sàng trải nghiệm bãi đỗ xe của',
    ctaTitle2: 'tương lai?',
    ctaSubtitle: 'Hàng ngàn khách hàng đã chuyển sang hệ thống quản lý thông minh. Tham gia mạng lưới của chúng tôi ngay hôm nay.',
    startBooking: 'Bắt đầu Đặt chỗ',
    footerArchitecture: 'Kiến trúc',
    footerNetwork: 'Mạng lưới',
    footerSecurity: 'Bảo mật',
    footerCopy: '© 2026 Thiết kế bởi PM System Global.',
    // Active session modal
    activeSessionTitle: 'Phiên đỗ đang hoạt động',
    activeSessionDesc: 'Bạn đang có một phiên đỗ xe chưa kết thúc (xe chưa ra khỏi bãi). Vui lòng hoàn tất thanh toán lối ra cho xe hiện tại trước khi thực hiện đặt chỗ mới.',
    viewCurrentSession: 'Xem phiên đỗ hiện tại',
    bookForAnotherCar: 'Đặt chỗ cho xe khác',
    close: 'Đóng',
    // ── Auth pages ──────────────────────────────────
    welcomeBack: 'Chào mừng trở lại',
    signInSubtitle: 'Đăng nhập để tiếp tục quản lý bãi đỗ xe thông minh',
    email: 'Email',
    password: 'Mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    signIn: 'Đăng nhập',
    orSignInWith: 'Hoặc đăng nhập với',
    noAccount: 'Chưa có tài khoản?',
    registerNow: 'Đăng ký ngay',
    createAccount: 'Tạo tài khoản',
    firstName: 'Tên',
    lastName: 'Họ',
    confirmPassword: 'Xác nhận mật khẩu',
    alreadyHaveAccount: 'Đã có tài khoản?',
    // ── Reservation page ────────────────────────────
    reservationTitle: 'Đặt chỗ giữ xe',
    reservationSubtitle: 'Thông tin để điều phối hệ thống nhận diện và loại phương tiện',
    parkingDate: 'Ngày gửi xe',
    startTime: 'Giờ bắt đầu',
    choosePlan: 'Chọn phương tiện đỗ',
    chooseLocation: 'Chọn vị trí / Bãi đỗ',
    nextStep: 'Tiếp theo',
    backStep: 'Quay lại',
    confirm: 'Xác nhận',
    // ── Profile page ────────────────────────────────
    personalInfo: 'Thông tin cá nhân',
    phoneNumber: 'Số điện thoại',
    address: 'Địa chỉ',
    licensePlate: 'Biển số xe',
    vehicleType: 'Loại phương tiện',
    save: 'Lưu thay đổi',
    saving: 'Đang lưu...',
    changeAvatar: 'Đổi ảnh đại diện',
    changePassword: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    // ── Common UI ───────────────────────────────────
    loading: 'Đang tải...',
    error: 'Lỗi',
    success: 'Thành công',
    cancel: 'Hủy',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    search: 'Tìm kiếm',
    filter: 'Lọc',
    export: 'Xuất',
    noData: 'Không có dữ liệu',
    back: 'Quay lại',
    next: 'Tiếp theo',
    submit: 'Gửi',
    update: 'Cập nhật',
    // ── Admin ───────────────────────────────────────
    dashboard: 'Tổng quan',
    monitoring: 'Giám sát',
    reservations: 'Đặt chỗ',
    reports: 'Báo cáo',
    users: 'Người dùng',
    incidents: 'Sự cố',
    blacklist: 'Danh sách đen',
    adminSettings: 'Cài đặt hệ thống',
    staffGate: 'Cổng Staff (Máy quét)',
    helpCenter: 'Trung tâm Trợ giúp',
    backToHome: 'Quay lại trang chủ',
    // ── Admin sidebar nav ───────────────────────────
    adminNavDashboard: 'Tổng quan',
    adminNavReservations: 'Quản lý giao dịch đặt xe',
    adminNavMonitoring: 'Giám sát trực tiếp',
    adminNavReports: 'Quản lý Chi nhánh',
    adminNavIncidents: 'Sự cố hệ thống',
    adminNavUsers: 'Quản lý người dùng',
    adminNavBlacklist: 'Danh sách đen & Cảnh báo',
    adminNavSettings: 'Cài đặt',
    // ── AdminMonitoring ─────────────────────────────
    monitorTitle: 'Giám sát Bãi đỗ (Live Map)',
    monitorSubtitle: 'Theo dõi thời gian thực trạng thái toàn bộ vị trí đỗ xe của hệ thống.',
    selectBuilding: 'Chọn Tòa nhà để giám sát',
    floorLabel: 'Tầng',
    floorMap: 'Sơ đồ chi tiết',
    spotsPerFloor: 'vị trí / Tầng',
    legendAvailable: 'Trống',
    legendReserved: 'Đã Đặt',
    legendOccupied: 'Có Xe',
    legendMaintenance: 'Bảo trì',
    availableCount: 'Còn Trống',
    occupancyPercent: 'Tỷ lệ lấp đầy',
    slotActions: 'Thao tác vị trí',
    parkingSlot: 'Ô đỗ xe',
    statusLabel: 'Trạng thái',
    statusAvailable: 'Trống',
    statusOccupied: 'Đang có xe',
    statusReserved: 'Đã đặt chỗ',
    statusMaintenance: 'Bảo trì',
    unlockSlot: 'Mở khóa vị trí',
    lockSlot: 'Khóa bảo trì vị trí này',
    ticketManagement: 'Quản lý vé đỗ',
    viewCustomerInfo: 'Xem thông tin người đặt',
    hideCustomerInfo: 'Ẩn thông tin khách hàng',
    booker: 'Người đặt chỗ',
    noPhone: 'Không có SĐT',
    cancelTicket: 'Hủy bỏ vé đặt chỗ',
    changeSlot: 'Đổi sang vị trí khác',
    enterSlot: 'Nhập ô (VD: B5)',
    changeBtn: 'Đổi',
    sanhThang: 'SẢNH THANG',
    liftAndStairs: 'LIẤT & THANG',
    guestLabel: 'Khách',
    // ── ReservationPage ─────────────────────────────
    reserveStep1: 'BƯỚc 1: NHẬP THÔNG TIN',
    reserveStep2: 'BƯỚc 2: HOÀN THIỆN THÔNG TIN',
    reserveHeading: 'Đăng ký giữ chỗ',
    reserveSubtitle: 'Thiết lập thời gian và vị trí đỗ xe thông minh chỉ trong vài giây.',
    chooseParkingDate: 'Ngày gửi xe',
    chooseStartTime: 'Giờ bắt đầu',
    chooseEndTime: 'Giờ kết thúc',
    selectVehicle: 'Chọn phương tiện gửi',
    selectYourCar: 'Chọn xe của bạn',
    addOtherPlate: '+ Nhập biển số xe khác',
    plateLabelShort: 'Biển số xe',
    selectParkingLot: 'Chọn vị trí / bãi đỗ',
    vehicleTypeLabel: 'Loại phương tiện',
    sedan: 'Ô tô 4-7',
    suv: 'SUV/Tải',
    motorbike: 'Xe máy',
    carLabel: 'Ô tô',
    motorbikeLabel: 'Xe máy',
    bikeLabel: 'Xe đạp/Xe điện',
    parkedBadge: 'Đang gửi',
    selectedSlot: 'Vị trí đã chọn',
    changeSlotLabel: 'Thay đổi',
    nextToPayment: 'TIẾP THEO: ĐI TỚI THANH TOÁN',
    nextToSelectSlot: 'TIẾP THEO: CHẬN VỊ TRÍ CHI TIẾT',
    mapLabel: 'BẢN ĐỒ',
    digitalTwinTitle: 'Thông số Bãi Đỗ Số Hóa',
    infraMonitor: 'Giám sát hạ tầng thời gian thực',
    floorLocate: 'Tầng định vị',
    block: 'Phân Khu',
    gps: 'Tọa độ GPS',
    autoSyncInfo: 'Hệ thống tự động đồng bộ biển số xe và loại phương tiện từ thông tin cá nhân của bạn để tối ưu thời gian thao tác.',
    // ── ProfilePage ─────────────────────────────────
    profileTitle: 'Hồ sơ cá nhân',
    profileSubtitle: 'Quản lý thông tin cá nhân và bảo mật tài khoản',
    basicInfo: 'Thông tin cơ bản',
    securitySettings: 'Cài đặt bảo mật',
    updateProfile: 'Cập nhật hồ sơ',
    saveChanges: 'Lưu thay đổi',
    changeAvatarBtn: 'Đổi ảnh',
    oldPassword: 'Mật khẩu hiện tại',
    newPasswordLabel: 'Mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
    updatePassword: 'Cập nhật mật khẩu',
    profileSaved: 'Hồ sơ đã được cập nhật!',
    // ── ActiveSessionPage ──────────────────────────
    activeSessionPageTitle: 'Phiên đỗ xe hoạt động',
    activeSessionPageSubtitle: 'Theo dõi trạng thái và quản lý phiên gửi xe của bạn.',
    noActiveSession: 'Không có phiên đỗ xe hoạt động',
    noActiveSessionDesc: 'Bạn chưa có phiên đỗ xe nào. Hãy đặt chỗ ngay!',
    bookNowBtn: 'Đặt chỗ ngay',
    checkedIn: 'Đã vào bãi',
    notCheckedIn: 'Chưa vào bãi',
    sessionDetails: 'Chi tiết phiên',
    viewQr: 'Xem mã QR',
    exitParking: 'Ra khỏi bãi',
    cancelSession: 'Hủy phiên đặt chỗ',
    // ── PricingPage ─────────────────────────────────
    pricingTitle: 'Bảng giá dịch vụ',
    pricingSubtitle: 'Lựa chọn gói phù hợp với nhu cầu đỗ xe của bạn',
    perHour: '/giờ',
    perDay: '/ngày',
    getStarted: 'Bắt đầu',
    // ── ContactPage ─────────────────────────────────
    contactTitle: 'Liên hệ với chúng tôi',
    contactSubtitle: 'Chúng tôi luôn sẵn sàng hỗ trợ bạn',
    yourName: 'Họ tên',
    yourEmail: 'Email của bạn',
    yourMessage: 'Nội dung',
    sendMessage: 'Gửi tin nhắn',
    // ── Auth pages ─────────────────────────────────
    signInBtn: 'Đăng nhập',
    registerBtn: 'Đăng ký',
    forgotPasswordTitle: 'Quên mật khẩu',
    forgotPasswordDesc: 'Nhập email của bạn để nhận liên kết đặt lại mật khẩu.',
    sendResetLink: 'Gửi liên kết đặt lại',
    backToLogin: 'Quay lại đăng nhập',
    // ── AdminDashboard ───────────────────────────
    dashboardTitle: 'Tổng quan hệ thống',
    dashboardSubtitle: 'Theo dõi hiệu suất và trạng thái hoạt động',
    totalRevenue: 'Tổng doanh thu',
    totalSessions: 'Tổng phiên đỗ',
    activeSessions: 'Phiên đang hoạt động',
    totalUsers: 'Tổng người dùng',
    recentActivity: 'Hoạt động gần đây',
    systemStatus: 'Trạng thái hệ thống',
    // ── Admin Reservations ──────────────────────────
    adminReservTitle: 'Quản lý giao dịch đặt xe',
    adminReservSubtitle: 'Xem và quản lý toàn bộ phiên đặt chỗ',
    searchPlaceholder: 'Tìm kiếm...',
    allStatus: 'Tất cả trạng thái',
    statusActive: 'Hoạt động',
    statusCompleted: 'Hoàn thành',
    statusCancelled: 'Hủy bỏ',
    // ── Admin Users ─────────────────────────────────
    adminUsersTitle: 'Quản lý người dùng',
    adminUsersSubtitle: 'Danh sách tài khoản và phân quyền trong hệ thống',
    role: 'Vai trò',
    joined: 'Ngày tham gia',
    allRoles: 'Tất cả vai trò',
    // ── AdminIncidents ─────────────────────────────
    incidentsTitle: 'Quản lý sự cố',
    incidentsSubtitle: 'Xem và xử lý các sự cố được báo cáo từ người dùng',
    resolve: 'Xác nhận xử lý',
    resolved: 'Đã xử lý',
    pending: 'Chờ xử lý',
    // ── ParkingStatus ──────────────────────────────
    parkingStatusTitle: 'Trạng thái bãi đỗ',
    parkingStatusSubtitle: 'Xem trạng thái các vị trí đỗ xe hiện tại',
    available: 'Trống',
    reserved: 'Đã đặt',
    occupied: 'Có xe',
    maintenance: 'Bảo trì',
    selectSlot: 'Chọn vị trí này',
    // ── PaymentPage ────────────────────────────────
    paymentTitle: 'Thanh toán',
    paymentSubtitle: 'Hoàn tất đặt chỗ của bạn',
    orderSummary: 'Tóm tắt đơn hàng',
    totalAmount: 'Tổng cộng',
    payNow: 'Thanh toán ngay',
    payWithVnPay: 'Thanh toán qua VNPay',
    // ── SuccessPage ────────────────────────────────
    bookingSuccess: 'Đặt chỗ thành công!',
    bookingSuccessDesc: 'Phiên đỗ xe của bạn đã được xác nhận.',
    viewMySession: 'Xem phiên của tôi',
    goHome: 'Về trang chủ',
    // ── ProfilePage extra keys (non-duplicate) ────────────────────
    phonePlaceholder: 'VD: 0987654321',
    addressPlaceholder: 'VD: Số 1 Đường ABC, Quận 7, TP.HCM',
    vehicleInfo: 'Thông tin phương tiện',
    confirmDelete: 'Xác nhận xóa xe',
    confirmDeleteDesc: 'Bạn có chắc chắn muốn xóa xe biển số',
    unsavedChanges: 'Thay đổi chưa lưu',
    unsavedChangesDesc: 'Bạn có thay đổi chưa lưu. Nếu rời đi bây giờ, thay đổi sẽ bị hủy bỏ.',
    stay: 'ở lại',
    leaveDiscard: 'Rời đi & Hủy lưu',
    imageTooLarge: 'Kích thước ảnh không được vượt quá 2MB',
    updateRequired: 'Cập nhật thông tin bắt buộc',
    updateRequiredDescription: 'Để đảm bảo an ninh bãi xe, quý khách vui lòng cập nhật đầy đủ thông tin: Họ tên, Số điện thoại, Biển số xe, Loại xe và Địa chỉ trước khi tiếp tục.',
  },
  en: {
    // ── Navbar ──────────────────────────────────────
    home: 'Home',
    status: 'Status',
    contact: 'Contact',
    login: 'Login',
    register: 'Register Now',
    hello: 'Hello,',
    profile: 'My Profile',
    history: 'Parking History',
    reportIncident: 'Report Incident',
    logout: 'Logout',
    // ── Settings dropdown ───────────────────────────
    settings: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    vietnamese: 'Tiếng Việt',
    english: 'English',
    // ── LandingPage ─────────────────────────────────
    heroTitle1: 'Smart',
    heroTitle2: 'Parking Management',
    heroTitle3: 'System',
    heroSubtitle: 'The next generation of infrastructure management. Experience seamless optimization powered by cutting-edge AI architecture.',
    bookNow: 'Book Now',
    viewPricing: 'View Pricing',
    statUptime: 'Uptime',
    statSpots: 'Available Spots',
    statProcessing: 'Processing Time',
    statDataPoints: 'Data Points',
    occupancyRate: 'Occupancy Rate',
    optimal: 'Optimal',
    coreTech: 'Core Technology',
    featuresTitle1: 'A touchless',
    featuresTitle2: 'parking experience',
    featuresDesc: 'PM System integrates the most advanced AI & IoT technology, delivering a comprehensive and 100% automated parking management solution.',
    feat1Title: 'Instant AI Recognition',
    feat1Desc: 'AI cameras read license plates in 0.2s, automatically opening barriers — no paper tickets, no waiting.',
    feat2Title: 'Digital Twin Map',
    feat2Desc: 'Real-time infrastructure monitoring. Updates each parking spot status with second-level precision.',
    feat3Title: 'Cashless Payments',
    feat3Desc: 'VNPay integrated, auto-charges via QR code. Customers exit easily without cash.',
    howItWorksTitle1: 'A streamlined',
    howItWorksTitle2: 'process',
    howItWorksSubtitle: 'In just 3 simple steps, all your parking procedures are completed fully automatically.',
    step1Title: 'Book in Advance',
    step1Desc: 'Choose your parking lot and spot via an interactive online map on your phone.',
    step2Title: 'Scan & Recognize',
    step2Desc: 'AI cameras at the gate automatically recognize license plates and grant access.',
    step3Title: 'Auto Payment',
    step3Desc: 'When your car exits, the system reconciles the time and deducts payment automatically.',
    ctaTitle1: 'Ready to experience the parking lot of the',
    ctaTitle2: 'future?',
    ctaSubtitle: 'Thousands of customers have switched to our smart management system. Join our network today.',
    startBooking: 'Start Booking',
    footerArchitecture: 'Architecture',
    footerNetwork: 'Network',
    footerSecurity: 'Security',
    footerCopy: '© 2026 Designed by PM System Global.',
    // Active session modal
    activeSessionTitle: 'Active Parking Session',
    activeSessionDesc: 'You have an ongoing parking session (vehicle still in lot). Please complete the exit payment for your current vehicle before making a new booking.',
    viewCurrentSession: 'View Current Session',
    bookForAnotherCar: 'Book for Another Car',
    close: 'Close',
    // ── Auth pages ──────────────────────────────────
    welcomeBack: 'Welcome Back',
    signInSubtitle: 'Sign in to continue managing your smart parking system',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign In',
    orSignInWith: 'Or sign in with',
    noAccount: "Don't have an account?",
    registerNow: 'Register Now',
    createAccount: 'Create Account',
    firstName: 'First Name',
    lastName: 'Last Name',
    confirmPassword: 'Confirm Password',
    alreadyHaveAccount: 'Already have an account?',
    // ── Reservation page ────────────────────────────
    reservationTitle: 'Reserve a Parking Spot',
    reservationSubtitle: 'Information for license plate recognition and vehicle type coordination',
    parkingDate: 'Parking Date',
    startTime: 'Start Time',
    choosePlan: 'Choose Vehicle',
    chooseLocation: 'Choose Location / Lot',
    nextStep: 'Next',
    backStep: 'Back',
    confirm: 'Confirm',
    // ── Profile page ────────────────────────────────
    personalInfo: 'Personal Information',
    phoneNumber: 'Phone Number',
    address: 'Address',
    licensePlate: 'License Plate',
    vehicleType: 'Vehicle Type',
    save: 'Save Changes',
    saving: 'Saving...',
    changeAvatar: 'Change Avatar',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    // ── Common UI ───────────────────────────────────
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    noData: 'No data available',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    update: 'Update',
    // ── Admin ───────────────────────────────────────
    dashboard: 'Dashboard',
    monitoring: 'Monitoring',
    reservations: 'Reservations',
    reports: 'Reports',
    users: 'Users',
    incidents: 'Incidents',
    blacklist: 'Blacklist',
    adminSettings: 'System Settings',
    staffGate: 'Staff Gate (Scanner)',
    helpCenter: 'Help Center',
    backToHome: 'Back to Home',
    // ── Admin sidebar nav ───────────────────────────
    adminNavDashboard: 'Dashboard',
    adminNavReservations: 'Transaction Management',
    adminNavMonitoring: 'Live Monitoring',
    adminNavReports: 'Branch Management',
    adminNavIncidents: 'System Incidents',
    adminNavUsers: 'User Management',
    adminNavBlacklist: 'Blacklist & Alerts',
    adminNavSettings: 'Settings',
    // ── AdminMonitoring ─────────────────────────────
    monitorTitle: 'Parking Lot Monitor (Live Map)',
    monitorSubtitle: 'Real-time tracking of all parking spot statuses in the system.',
    selectBuilding: 'Select Building to Monitor',
    floorLabel: 'Floor',
    floorMap: 'Detailed Floor Map',
    spotsPerFloor: 'spots / Floor',
    legendAvailable: 'Available',
    legendReserved: 'Reserved',
    legendOccupied: 'Occupied',
    legendMaintenance: 'Maintenance',
    availableCount: 'Available',
    occupancyPercent: 'Occupancy Rate',
    slotActions: 'Slot Actions',
    parkingSlot: 'Parking Slot',
    statusLabel: 'Status',
    statusAvailable: 'Available',
    statusOccupied: 'Occupied',
    statusReserved: 'Reserved',
    statusMaintenance: 'Maintenance',
    unlockSlot: 'Unlock Slot',
    lockSlot: 'Lock for Maintenance',
    ticketManagement: 'Ticket Management',
    viewCustomerInfo: 'View Booker Info',
    hideCustomerInfo: 'Hide Customer Info',
    booker: 'Booker',
    noPhone: 'No Phone',
    cancelTicket: 'Cancel Reservation',
    changeSlot: 'Move to Another Slot',
    enterSlot: 'Enter slot (e.g. B5)',
    changeBtn: 'Move',
    sanhThang: 'LIFT CORE',
    liftAndStairs: 'LIFT & STAIRS',
    guestLabel: 'Guest',
    // ── ReservationPage ─────────────────────────────
    reserveStep1: 'STEP 1: ENTER INFORMATION',
    reserveStep2: 'STEP 2: COMPLETE INFORMATION',
    reserveHeading: 'Reserve a Parking Spot',
    reserveSubtitle: 'Set up your parking time and location in just a few seconds.',
    chooseParkingDate: 'Parking Date',
    chooseStartTime: 'Start Time',
    chooseEndTime: 'End Time',
    selectVehicle: 'Select Vehicle',
    selectYourCar: 'Select your vehicle',
    addOtherPlate: '+ Enter another plate',
    plateLabelShort: 'License Plate',
    selectParkingLot: 'Select Location / Lot',
    vehicleTypeLabel: 'Vehicle Type',
    sedan: 'Sedan 4-7',
    suv: 'SUV/Truck',
    motorbike: 'Motorbike',
    carLabel: 'Car',
    motorbikeLabel: 'Motorbike',
    bikeLabel: 'Bicycle/E-bike',
    parkedBadge: 'Parked',
    selectedSlot: 'Selected Slot',
    changeSlotLabel: 'Change',
    nextToPayment: 'NEXT: GO TO PAYMENT',
    nextToSelectSlot: 'NEXT: SELECT DETAILED SLOT',
    mapLabel: 'MAP',
    digitalTwinTitle: 'Digital Twin Parking Stats',
    infraMonitor: 'Real-time Infrastructure Monitor',
    floorLocate: 'Floor',
    block: 'Block',
    gps: 'GPS Coordinates',
    autoSyncInfo: 'The system automatically syncs your license plate and vehicle type from your profile to optimize processing time.',
    // ── ProfilePage ─────────────────────────────────
    profileTitle: 'My Profile',
    profileSubtitle: 'Manage your personal information and account security',
    basicInfo: 'Basic Information',
    securitySettings: 'Security Settings',
    updateProfile: 'Update Profile',
    saveChanges: 'Save Changes',
    changeAvatarBtn: 'Change Photo',
    oldPassword: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    profileSaved: 'Profile updated successfully!',
    // ── ActiveSessionPage ──────────────────────────
    activeSessionPageTitle: 'Active Parking Session',
    activeSessionPageSubtitle: 'Track status and manage your parking session.',
    noActiveSession: 'No active parking session',
    noActiveSessionDesc: 'You have no active parking session. Book a spot now!',
    bookNowBtn: 'Book Now',
    checkedIn: 'Checked In',
    notCheckedIn: 'Not Checked In',
    sessionDetails: 'Session Details',
    viewQr: 'View QR Code',
    exitParking: 'Exit Parking',
    cancelSession: 'Cancel Booking',
    // ── PricingPage ─────────────────────────────────
    pricingTitle: 'Service Pricing',
    pricingSubtitle: 'Choose the plan that fits your parking needs',
    perHour: '/hour',
    perDay: '/day',
    getStarted: 'Get Started',
    // ── ContactPage ─────────────────────────────────
    contactTitle: 'Contact Us',
    contactSubtitle: 'We are always ready to help you',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourMessage: 'Message',
    sendMessage: 'Send Message',
    // ── Auth pages ─────────────────────────────────
    signInBtn: 'Sign In',
    registerBtn: 'Register',
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordDesc: 'Enter your email to receive a password reset link.',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    // ── AdminDashboard ───────────────────────────
    dashboardTitle: 'System Overview',
    dashboardSubtitle: 'Monitor performance and operational status',
    totalRevenue: 'Total Revenue',
    totalSessions: 'Total Sessions',
    activeSessions: 'Active Sessions',
    totalUsers: 'Total Users',
    recentActivity: 'Recent Activity',
    systemStatus: 'System Status',
    // ── Admin Reservations ──────────────────────────
    adminReservTitle: 'Reservation Management',
    adminReservSubtitle: 'View and manage all parking bookings',
    searchPlaceholder: 'Search...',
    allStatus: 'All Statuses',
    statusActive: 'Active',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    // ── Admin Users ─────────────────────────────────
    adminUsersTitle: 'User Management',
    adminUsersSubtitle: 'Account list and permission management in the system',
    role: 'Role',
    joined: 'Date Joined',
    allRoles: 'All Roles',
    // ── AdminIncidents ─────────────────────────────
    incidentsTitle: 'Incident Management',
    incidentsSubtitle: 'View and handle incidents reported by users',
    resolve: 'Mark as Resolved',
    resolved: 'Resolved',
    pending: 'Pending',
    // ── ParkingStatus ──────────────────────────────
    parkingStatusTitle: 'Parking Status',
    parkingStatusSubtitle: 'View current availability of parking spots',
    available: 'Available',
    reserved: 'Reserved',
    occupied: 'Occupied',
    maintenance: 'Maintenance',
    selectSlot: 'Select This Spot',
    // ── PaymentPage ────────────────────────────────
    paymentTitle: 'Payment',
    paymentSubtitle: 'Complete your booking',
    orderSummary: 'Order Summary',
    totalAmount: 'Total',
    payNow: 'Pay Now',
    payWithVnPay: 'Pay with VNPay',
    // ── SuccessPage ────────────────────────────────
    bookingSuccess: 'Booking Successful!',
    bookingSuccessDesc: 'Your parking session has been confirmed.',
    viewMySession: 'View My Session',
    goHome: 'Go to Home',
    // ── ProfilePage extra keys (non-duplicate) ────────────────────
    phonePlaceholder: 'e.g. 0987654321',
    addressPlaceholder: 'e.g. 123 Main St, District 7, HCMC',
    vehicleInfo: 'Vehicle Information',
    confirmDelete: 'Confirm Remove Vehicle',
    confirmDeleteDesc: 'Are you sure you want to remove the vehicle with plate',
    unsavedChanges: 'Unsaved Changes',
    unsavedChangesDesc: 'You have unsaved changes. If you leave now, your changes will be discarded.',
    stay: 'Stay',
    leaveDiscard: 'Leave & Discard',
    imageTooLarge: 'Image size must not exceed 2MB',
    updateRequired: 'Profile Update Required',
    updateRequiredDescription: 'To ensure parking security, please update your full details: Full name, Phone number, License plate, Vehicle type, and Address before continuing.',
  },
};

interface SettingsContextType {
  theme: Theme;
  language: Language;
  toggleTheme: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | null>(null);

export const SettingsProvider = ({ children }: { children: React.ReactNode }) => {
  const [theme, setTheme] = useState<Theme>(() => {
    return (localStorage.getItem('pm-theme') as Theme) || 'light';
  });

  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('pm-language') as Language) || 'vi';
  });

  // Apply dark class on <html> whenever theme changes
  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('pm-theme', theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme((prev) => (prev === 'light' ? 'dark' : 'light'));
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pm-language', lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language][key] || key;
  };

  return (
    <SettingsContext.Provider value={{ theme, language, toggleTheme, setLanguage, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = (): SettingsContextType => {
  const ctx = useContext(SettingsContext);
  if (!ctx) {
    throw new Error('useSettings must be used within a SettingsProvider');
  }
  return ctx;
};
