/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline": "#727687",
        "surface-dim": "#cbdbf5",
        "error": "#ba1a1a",
        "inverse-surface": "#213145",
        "on-tertiary-fixed": "#191c1e",
        "on-surface": "#0b1c30",
        "primary-fixed": "#dae1ff",
        "tertiary-fixed-dim": "#c4c7c9",
        "tertiary-fixed": "#e0e3e5",
        "on-secondary-container": "#5c647a",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "primary-container": "#0066ff",
        "inverse-primary": "#b3c5ff",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c2c6d8",
        "tertiary": "#565a5b",
        "secondary-container": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0054d6",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003fa4",
        "primary": "#0050cb",
        "secondary": "#565e74",
        "secondary-fixed": "#dae2fd",
        "on-surface-variant": "#424656",
        "on-background": "#0b1c30",
        "on-primary-container": "#f8f7ff",
        "on-tertiary-fixed-variant": "#444749",
        "tertiary-container": "#6f7274",
        "surface-variant": "#d3e4fe",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001849",
        "on-secondary-fixed": "#131b2e",
        "background": "#f8f9ff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#f6f8fa",
        "on-error-container": "#93000a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "section-gap": "64px",
        "unit": "4px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-edge": "40px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "data-mono": ["Inter"],
        "body-sm": ["Inter"],
        "headline-xl": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "data-mono": ["14px", { "lineHeight": "1.0", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-xl": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
